spring:
  application:
    name: finance-tracker-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:102715}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
